### ISSUE TITLE
.moved files

### ISSUE THREAD

**Issue by yarikoptic** [dandisets/000108#1]
alerted to by @TheChymera

dandiset has a number of files with `.moved` extension

<details>
<summary>full list on this datalad dandiset as of ecf5a79083cd38924b41bae48d0d14e6384dd824</summary> 

```shell
(git-annex)lena:~/proj/dandi/dandisets/000108[draft]git-annex
$> find -iname *.moved
./sub-MITU01/ses-20210915h15m45s27/microscopy/sub-MITU01_ses-20210915h15m45s27_run-1_sample-109_stain-YO_chunk-8_spim.h5.moved
./sub-MITU01/ses-20210915h15m45s27/microscopy/sub-MITU01_ses-20210915h15m45s27_run-1_sample-109_stain-LEC_chunk-11_spim.h5.moved
./sub-MITU01/ses-20210910h16m27s07/microscopy/sub-MITU01_ses-20210910h16m27s07_run-1_sample-110_stain-NN_chunk-1_spim.h5.moved
./sub-MITU01/ses-20210910h16m27s07/microscopy/sub-MITU01_ses-20210910h16m27s07_run-1_sample-110_stain-NN_chunk-2_spim.h5.moved
./sub-MITU01/ses-20210910h16m27s07/microscopy/sub-MITU01_ses-20210910h16m27s07_run-1_sample-110_stain-NN_chunk-3_spim.h5.moved
./sub-MITU01/ses-20210910h16m27s07/microscopy/sub-MITU01_ses-20210910h16m27s07_run-1_sample-110_stain-NN_chunk-4_spim.h5.moved
./sub-MITU01/ses-20210910h16m27s07/microscopy/sub-MITU01_ses-20210910h16m27s07_run-1_sample-110_stain-NN_chunk-5_spim.h5.moved
./sub-MITU01/ses-20210910h16m27s07/microscopy/sub-MITU01_ses-20210910h16m27s07_run-1_sample-110_stain-NN_chunk-6_spim.h5.moved
./sub-MITU01/ses-20210919h18m20s55/microscopy/sub-MITU01_ses-20210919h18m20s55_run-1_sample-90_stain-YO_chunk-1_spim.h5.moved

```
</details>

which could also be seen (checked on one) e.g. at https://gui.dandiarchive.org/#/dandiset/000108/draft/files?location=sub-MITU01%2Fses-20210915h15m45s27%2Fmicroscopy%2F so it is not some kind of a bug in our dataladification.

@LeeKamentsky should they be removed or somehow renamed?

**Comment by LeeKamentsky** [comment]
Thanks Yari,
They should be removed. I don't have any idea how they got there - they do have @satra as owner on our mirrored local copy. Also they are for some, but not all of the .h5 files in the directory. The dates on the .moved versions are about 2 weeks prior to those on the corresponding .h5 file and the two files are definitely not the same, but of 90% of the same size. We did have some issues with files that were corrupted in the transfer to DANDI and I have a feeling that I moved the corrupted files, recreated them, but forgot to delete the moved versions.

Any quick way I could do the removal? (or you?)

**Comment by yarikoptic** [comment]
let's wait for @satra's blessing first (could we just remove them @satra?)

then, `dandi delete */*.moved` I think should do the trick if you have them locally; I could also try based on an "empty" clone of this repo -- should work too (if doesn't -- we would need to fix that ;)) but that would leave those copies on your system which you might later reupload again ;)

**Comment by satra** [comment]
yes, those moved files should be deleted.

**Comment by TheChymera** [comment]
I think there are not more `*.moved` files in the repository.

**Comment by yarikoptic** [comment]
correct
