### ISSUE TITLE
Subject field inconsistency between `sub-MITU01` directory and `sub-MITU01h3` filename

### ISSUE THREAD

**Issue by TheChymera** [dandisets/000108#10]
```
sub-MITU01/ses-20220309h18m20s33/micr/sub-MITU01h3_ses-20220309h18m20s33_sample-17_stain-YO_run-1_chunk-8_SPIM.json
```

This is an example of `sub-MITU01h3` files.
@satra — this is why I concluded this was an error, and [attempted a parsing fix for metadata generation](https://github.com/dandi/dandi-cli/blob/1ae0a3b2a8ab407b9f7347ba0d7e33c3b627fc87/dandi/bids_utils.py#L124).

**Comment by satra** [comment]
i would say this is an example that the validator would flag, but it would still trust the top level name as the sub name.

@slaytonmarx - this probably requires some kind of internal investigation on your side as to which subject the sample/session combo belonged to.

**Comment by yarikoptic** [comment]
I hope that validator would catch them now, but looking at the current listing -- it seems that issue is no longer present

```
$> jq '.[].path' < /tmp/000108-all.json | grep "sub-" | grep -v 'sub-\(.*\)/ses-\(.*\)/sub-\1_ses-.*_.*'
"sub-MITU01/sub-MITU01_sessions.tsv"
"sub-MITU01/ses-20220104h13m37s33/micr/sub-MITU01_sample-50_photo.jpg"
"sub-MITU01/ses-20220103h10m16s20/micr/sub-MITU01_sample-68_photo.jpg"
"sub-MITU01/ses-20220321h14m52s06/micr/sub-MITU01_sample-23_photo.jpg"
```
