### ISSUE TITLE
`SPIM` suffix should be uppercase.

### ISSUE THREAD

**Issue by TheChymera** [dandisets/000108#4]
e.g.

```
./sub-MITU01/ses-20210704h21m07s40/microscopy/sub-MITU01_ses-20210704h21m07s40_run-1_sample-159_stain-YO_chunk-10_SPIM.json
```

instead of 

```
./sub-MITU01/ses-20210704h21m07s40/microscopy/sub-MITU01_ses-20210704h21m07s40_run-1_sample-159_stain-YO_chunk-10_spim.json
```

As per: https://github.com/bids-standard/bids-specification/commit/6a60eb2f52359b84443c6fa8925d724dbc737fef#diff-efd2412ecbcf4cc75cf7de0fdc5ca64923ecfa9ccc32b4463ce8f6407e9fa30fR20

And discussed: https://github.com/bids-standard/bids-specification/pull/881#issuecomment-1013710837

**Comment by satra** [comment]
isn't this already fixed?

**Comment by TheChymera** [comment]
yes, it is.
