### ISSUE TITLE
microscopy `_photo` suffix files need to either not have a `_run-` entity, or have it after `_sample-` and `_acq-`. 

### ISSUE THREAD

**Issue by TheChymera** [dandisets/000108#7]
The archive contains many files of the form `./sub-MITU01/ses-20210813h22m03s27/microscopy/sub-MITU01_ses-20210813h22m03s27_run-1_sample-121_photo.jpg`. As per current BIDS, `_photo` suffix files do not support a `_run-` entity.

We'll [try to add this to the specification](https://github.com/bids-standard/bids-specification/issues/992), since theoretically, there is no good reason to invalidate photos of multiple runs, however, inspecting the collection, there are never different runs for these files, they are all `_run-1`. So independently of that, it might be best to remove the entity from this dataset specifically.

If you would wish to keep it, it would need to be added *after* the `_sample-` (and, if present, though again, that does not seem to be the case here) and the `_acq-` entities.

**Comment by Remi-Gau** [comment]
For the record:

The absolute order of all the entities in BIDS files is listed here in the schema:
https://github.com/bids-standard/bids-specification/blob/master/src/schema/rules/entities.yaml

This is rendered in the specification in this page (see the same absolute order in the right hand column):
https://bids-specification.readthedocs.io/en/stable/99-appendices/09-entities.html

**Comment by LeeKamentsky** [comment]
Removed "run" from all existing photos in preparation for upload. @satra but maybe this had already been done? Now setting to work to change "microscopy" to "micr" and sub-*_ses-*_run-*_sample-*_stain-*_chunk-*_spim.* to sub-*_ses-*_sample-*_stain-*_run-*_chunk-*_SPIM.*

**Comment by satra** [comment]
thank you @LeeKamentsky - i think you can use @TheChymera 's script to check the dataset after you make these changes. @TheChymera - are there instructions that @LeeKamentsky could follow?

@LeeKamentsky - we should ignore my changes in the hdf5 side at this point and just focus on your dandi+ngff dataset and get that conformant. thus, to all intents and purposes consider my hacks of session/name change moot :)

**Comment by TheChymera** [comment]
The original issue has been fixed, as well as a subsequent issue consisting in missing session entries in the file name (which are mandatory if there are session subdirectories).
